import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { after } from "next/server";
import { log } from "./utils";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  after(() => {
    // Execute after the layout is rendered and sent to the user
    log('ON:RootLayout.after');
  });

  return (
    <html lang="zh-hant">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <Link href="/" className="px-2">首頁</Link>
          <Link href="/contact" className="px-2 border-l">聯絡我</Link>
          <Link href="/about" className="px-2 border-l">關於我</Link>
          <Link href="/users" className="px-2 border-l">用戶</Link>
        </header>
        <article>
          {children}
        </article>
      </body>
    </html>
  );
}
